### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by hopeseekr** [sebastianbergmann/code-unit#7]
As a function of the Bettergist Collective, every quarter I run tests on every Packagist project with sufficient installs.

The project reports total failure to install this as a normal dev package.

To reproduce:

```
git clone --depth=1 https://github.com/sebastianbergmann/code-unit.git
cd code-unit
PHP_VERSION=8.2 composer install
```

**Expected:** Installation would succeed.

**Actual:**

> Updating dependencies
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Root composer.json requires phpunit/phpunit ^11.0 -> satisfiable by phpunit/phpunit[11.0.0, ..., 11.0.8].
>     - phpunit/phpunit[11.0.0, ..., 11.0.8] require sebastian/code-unit ^3.0 -> satisfiable by sebastian/code-unit[3.0.0] from composer repo (https://repo.packagist.org) but sebastian/code-unit is the root package and cannot be modified. See https://getcomposer.org/dep-on-root for details and assistance.

**Comment by hopeseekr** [comment]
It's a weird one. It almost looks like a composer bug... Cloning the repo and composer install works fine...

**Comment by sebastianbergmann** [comment]
This is not an issue with this library, sorry.

**Comment by hopeseekr** [comment]
I apologize, too.

**Comment by hopeseekr** [comment]
@sebastianbergmann To reproduce, simply remove or move the `.git` directory. it is a legit composer bug. Not sure why it affects this repo and not every package. Maybe cyclical dependencies?
